namespace ColdFormedChannelSection.App.ViewModels.Enums
{
    internal enum Context
    {
        RESISTANCE_DIRECT_STRENGTH,
        RESISTANCE_EGYPT_CODE,
        RESISTANCE_EURO_CODE,
        RESISTANCE_AISI_CODE,
        RESISTANCE_AISC_CODE,
        CHECK_DIRECT_STRENGTH,
        CHECK_EGYPT_CODE,
        CHECK_EURO_CODE,
        CHECK_AISI_CODE,
        DESIGN_DIRECT_STRENGTH,
        DESIGN_EGYPT_CODE,
        DESIGN_EURO_CODE,
        DESIGN_AISI_CODE,
        STIFF_UNSTIFF,
        SECTION_GEOMETRY,
        UNITS,
        STRAININGACTIONS,
        ABOUT,
        DIRECT_STRENGTH,
        EFFECTIVE_WIDTH,
        HOME,
        BRACING,
            SA_MODULE
    }
}
